### ISSUE TITLE
[rush-lint-staged-plugin] Using project dependencies in .lintstagedrc.json

### ISSUE THREAD

**Issue by koen-dev** [bytesfriends/rush-plugins#23]
Apologies for the what confusing title (naming is hard). Let me start to say I am unsure if this issue is related to `rush-lint-staged-plugin` or `lint-staged`. My gut feeling tells me that it has to do with the rush plugin.

## Steps to reproduce
1. Have a monorepo with this plugin installed in `common/autoinstallers/**`
2. Add a project with it a `.lintstagedrc.json` in for example `apps/my-app`
3. Add a lint-staged config with for example this:
```json
{
  "*.{ts,tsx}": ["eslint --fix", "stylelint", "jest --bail --findRelatedTests"],
}
```
4. Make a change and stage the change
5. Run `rush lint-staged`

## Expected result
1. `rush lint-staged` correctly picks up the changes and the uses the related `.lintstagedrc.json`
2. lint-staged uses the dependencies provided by the package it is running for in this case `apps/my-app`

## Actual result
1. `rush lint-staged` correctly picks up the changes and the uses the related `.lintstagedrc.json`
2. lint-staged fails stylelint & jest because they are both not a dependency of the autoinstaller containing `rush-lint-staged-plugin` (eslint passes as it is a dependency of the package `rush-lint-staged-plugin`)
3. After adding `stylelint` to the autoinstaller and its needed dependencies like `postcss-scss` it runs correctly.
4. After adding `jest` to the autoinstaller it fails to load the correct config file

Ideally you want to use the dependencies that are needed per project for `lint-staged` perhaps I am missing the correct approach. I would love to hear if this is something that can be fixed either in my configuration or on the side of the plugin.

**Comment by chengcyber** [comment]
@koen-dev I can reproduce by following your steps. The tricky part is `lint-staged` behaves differently with the number of your `lint-staged` config files. If there is only one `.lintstagedrc.json` in `apps/my-apps`. `jest` would throws errors because the `cwd` of `jest` task equals to the root path of monorepo. While if there are multiple config files, the `cwd` of `jest` task will be changed to the directory of each config file, sth like `path.dirname(lintStagedConfigFile)`.

So, the workaround is adding a `.lintstargedrc.json` in your root path as a placeholder, this makes `lint-staged` always behaves as multiple config files found. Just like this one: https://github.com/bytesfriends/rush-plugins/blob/main/lint-staged.config.cjs

**Comment by chengcyber** [comment]
Close this because it's inactive
